
default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  username: postgres
  password: 123456
  pool: 5

development:
  <<: *default
  database: sentinela_backend_dev

 
test:
  <<: *default
  database: sentinela_backend_test


production:
  <<: *default
  database: sentinela_backend_production
  username: sentinela_backend
  password: <%= ENV['SENTINELA_BACKEND_DATABASE_PASSWORD'] %>
